version: "3.9"

services:
  db:
    image: postgres:15
    container_name: db
    env_file:
      - .env
  web:
    build:
      context: .
    env_file:
      - .env
    container_name: web
    ports:
      - 8000:8000
    depends_on:
      - db
    command: ["/order_status_management/app.sh"]
